### PR TITLE
Convert input to a number

### LINKED ISSUE #154: YAML config stringifies numbers
When you try to export `.yaml` config number values are quoted

``` yaml
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
  indent_size: '2'
  max_preserve_newlines: '1'
```

If I have numbers like that in my default config, plugin doesn't work.
When I remove quotes it works. 
Apparently you're expecting a number there and assistant outputs a string.

### PR DESCRIPTION
**Pull request by stevenzeck**
Closes #154.

### CODE REVIEW

**Comment by Glavin001** [comment]
Works great for me!

image

**Comment by Glavin001** [comment]
@fila90 would you test this to ensure #154 is fixed before we merge?

https://deploy-preview-158--unibeautify-assistant.netlify.com/#/setup

Thanks!

**Comment by fila90** [comment]
yupp, works great!!

one small issue kinda related to this, when you open `Indent Size` settings value is not set and you can set any number (eg. 555), once you set ti you can set only numbers between 0 - 4. If the number is greater than 4, interactive preview doesn't work.
maybe that should be also taken care of, probably in different PR.

**Comment by stevenzeck** [comment]
@fila90 what browser are you using?

**Comment by fila90** [comment]
latest version of Chrome

**Comment by stevenzeck** [comment]
Ok. It doesn't seem to validate when you first start inputting something. If you enter 5555, remove it, then try entering 5555 again, it doesn't take. I would say this is more of a browser issue, since we are relying on `input type="number"`

**Comment by Glavin001** [comment]
Thanks for fixing this, @stevenzeck ! 🎉

**Pull request merged**
