### PR TITLE
UI changes to Setup

### PR DESCRIPTION
**Pull request by szeck87**
* Replaced the jumbotron at the top of the wizard with something more space-saving
* The wizard step buttons do not move, they will always be at the bottom of each step
* In the screenshot, the two areas in the red boxes each scroll independently, the rest of the page stays as is
* Progress bar moved from the top to the right of the buttons
* Removed (# languages) from the sidemenu step name text, adjusted width of sidemenu

screen shot 2018-06-20 at 6 55 10 pm

Ideally...
* Download and Copy buttons are placed inside the CodeMirror component area or next to the Export configuration header

### CODE REVIEW

**Comment by Glavin001** [comment]
This is looking great!

If you are also able to fix the export page to be full height, that would be awesome. No worries, if not. Great job!

image

**Comment by Glavin001** [comment]
@szeck87 ignore the tall page. I used https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl and it must not have respected the left side menu scroll. It was cut off correctly when I looked at it 👍 . Don't worry about it.

**Comment by szeck87** [comment]
@Glavin001 this is as far as I want to go with this PR.  Let know your thoughts.

**Comment by Glavin001** [comment]
Just tried it out. Looks great! Thanks and great work as always, @szeck87 !

**Pull request merged**
